# Generated by Django 4.2.11 on 2025-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push"),
                            ("IN_APP", "In-App"),
                        ],
                        max_length=10,
                        verbose_name="Canal",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SENT", "Envoyé"),
                            ("DELIVERED", "Délivré"),
                            ("FAILED", "Échoué"),
                            ("READ", "Lu"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(blank=True, max_length=50, verbose_name="Type"),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type d'objet"
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID d'objet"
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Réponse fournisseur"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Envoyé le"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APT_CONFIRMED", "Rendez-vous confirmé"),
                            ("APT_REMINDER", "Rappel de rendez-vous"),
                            ("APT_CANCELLED", "Rendez-vous annulé"),
                            ("APP_RECEIVED", "Demande reçue"),
                            ("APP_STATUS", "Statut de demande modifié"),
                            ("APP_READY", "Demande prête"),
                            ("PAY_RECEIVED", "Paiement reçu"),
                            ("PAY_FAILED", "Paiement échoué"),
                            ("DOC_REQUIRED", "Document requis"),
                            ("ACC_VERIFY", "Vérification de compte"),
                            ("PWD_RESET", "Réinitialisation de mot de passe"),
                            ("GENERAL", "Général"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Type de notification",
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Sujet email"
                    ),
                ),
                (
                    "email_body",
                    models.TextField(blank=True, verbose_name="Corps email"),
                ),
                (
                    "email_html_body",
                    models.TextField(blank=True, verbose_name="Corps HTML email"),
                ),
                (
                    "sms_body",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="Corps SMS"
                    ),
                ),
                (
                    "push_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Titre push"
                    ),
                ),
                (
                    "push_body",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="Corps push"
                    ),
                ),
                (
                    "send_email",
                    models.BooleanField(default=True, verbose_name="Envoyer email"),
                ),
                (
                    "send_sms",
                    models.BooleanField(default=False, verbose_name="Envoyer SMS"),
                ),
                (
                    "send_push",
                    models.BooleanField(default=True, verbose_name="Envoyer push"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modèle de notification",
                "verbose_name_plural": "Modèles de notifications",
            },
        ),
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=255, unique=True, verbose_name="Token"),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom de l'appareil"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Type d'appareil"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière utilisation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil push",
                "verbose_name_plural": "Appareils push",
                "ordering": ["-last_used"],
            },
        ),
    ]
