# Generated by Django 4.2.11 on 2025-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de référence",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(verbose_name="Date du rendez-vous"),
                ),
                (
                    "appointment_time",
                    models.TimeField(verbose_name="Heure du rendez-vous"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=30, verbose_name="Durée (minutes)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmé"),
                            ("CHECKED_IN", "Enregistré"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("CANCELLED", "Annulé"),
                            ("NO_SHOW", "Absent"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(blank=True, verbose_name="Notes de l'utilisateur"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notes administratives"),
                ),
                (
                    "confirmation_sent",
                    models.BooleanField(
                        default=False, verbose_name="Confirmation envoyée"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, verbose_name="Rappel envoyé"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmé le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["-appointment_date", "-appointment_time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "max_appointments",
                    models.IntegerField(
                        default=1, verbose_name="Nombre maximum de rendez-vous"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Créneau de rendez-vous",
                "verbose_name_plural": "Créneaux de rendez-vous",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
