# Generated by Django 4.2.11 on 2025-10-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentslot",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_slots",
                to="core.consularoffice",
                verbose_name="Bureau consulaire",
            ),
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_slots",
                to="core.servicetype",
                verbose_name="Type de service",
            ),
        ),
    ]
