# Generated by Django 4.2.11 on 2025-10-13 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent assigné",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="core.consularoffice",
                verbose_name="Bureau consulaire",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="core.servicetype",
                verbose_name="Type de service",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentslot",
            unique_together={("office", "service_type", "date", "start_time")},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "appointment_time"],
                name="appointment_appoint_c5b816_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["user", "-appointment_date"],
                name="appointment_user_id_8c3095_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "appointment_date"],
                name="appointment_status_7c15d1_idx",
            ),
        ),
    ]
