# Generated by Django 4.2.11 on 2025-10-13 10:22

import applications.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de référence",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("VISA", "Visa"),
                            ("PASSPORT", "Passeport"),
                            ("PASSPORT_RENEWAL", "Renouvellement de passeport"),
                            ("BIRTH_CERT", "Acte de naissance"),
                            ("MARRIAGE_CERT", "Acte de mariage"),
                            ("LEGALIZATION", "Légalisation de document"),
                            ("ATTESTATION", "Attestation consulaire"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de demande",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SUBMITTED", "Soumis"),
                            ("UNDER_REVIEW", "En cours de vérification"),
                            ("INFO_REQUIRED", "Informations supplémentaires requises"),
                            ("PAYMENT_PENDING", "En attente de paiement"),
                            ("PAYMENT_RECEIVED", "Paiement reçu"),
                            ("PROCESSING", "En traitement"),
                            ("READY", "Prêt pour retrait"),
                            ("COMPLETED", "Terminé"),
                            ("REJECTED", "Rejeté"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "base_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Frais de base",
                    ),
                ),
                (
                    "additional_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Frais additionnels",
                    ),
                ),
                (
                    "total_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Frais totaux",
                    ),
                ),
                (
                    "applicant_notes",
                    models.TextField(blank=True, verbose_name="Notes du demandeur"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notes administratives"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motif de rejet"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Soumis le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Demande",
                "verbose_name_plural": "Demandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PASSPORT", "Passeport"),
                            ("ID_CARD", "Carte d'identité"),
                            ("PHOTO", "Photo d'identité"),
                            ("BIRTH_CERT", "Acte de naissance"),
                            ("MARRIAGE_CERT", "Acte de mariage"),
                            ("RESIDENCE", "Justificatif de domicile"),
                            ("INVITATION", "Lettre d'invitation"),
                            ("WORK_PERMIT", "Permis de travail"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=applications.models.get_document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                ("file_size", models.IntegerField(verbose_name="Taille (octets)")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vérifié le"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="Notes de vérification"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisaApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("TOURIST", "Tourisme"),
                            ("BUSINESS", "Affaires"),
                            ("WORK", "Travail"),
                            ("STUDY", "Études"),
                            ("FAMILY", "Regroupement familial"),
                            ("TRANSIT", "Transit"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de visa",
                    ),
                ),
                ("purpose_of_visit", models.TextField(verbose_name="Motif du voyage")),
                (
                    "intended_entry_date",
                    models.DateField(verbose_name="Date d'entrée prévue"),
                ),
                (
                    "intended_departure_date",
                    models.DateField(verbose_name="Date de sortie prévue"),
                ),
                ("duration_days", models.IntegerField(verbose_name="Durée (jours)")),
                (
                    "destination_city",
                    models.CharField(
                        max_length=100, verbose_name="Ville de destination"
                    ),
                ),
                (
                    "accommodation_address",
                    models.TextField(blank=True, verbose_name="Adresse d'hébergement"),
                ),
                (
                    "sponsor_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom du parrain"
                    ),
                ),
                (
                    "sponsor_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone du parrain"
                    ),
                ),
                (
                    "sponsor_address",
                    models.TextField(blank=True, verbose_name="Adresse du parrain"),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Profession"
                    ),
                ),
                (
                    "employer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Employeur"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_details",
                        to="applications.application",
                        verbose_name="Demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détails de visa",
                "verbose_name_plural": "Détails de visas",
            },
        ),
        migrations.CreateModel(
            name="PassportApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passport_type",
                    models.CharField(
                        choices=[
                            ("NEW", "Nouveau"),
                            ("RENEWAL", "Renouvellement"),
                            ("REPLACEMENT", "Remplacement"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Type de demande",
                    ),
                ),
                (
                    "current_passport_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Numéro de passeport actuel",
                    ),
                ),
                (
                    "current_passport_issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de délivrance"
                    ),
                ),
                (
                    "current_passport_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "replacement_reason",
                    models.TextField(blank=True, verbose_name="Motif de remplacement"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport_details",
                        to="applications.application",
                        verbose_name="Demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détails de passeport",
                "verbose_name_plural": "Détails de passeports",
            },
        ),
    ]
