# Generated by Django 4.2.11 on 2025-10-13 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vérifié par",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Demandeur",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent assigné",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="applications",
                to="applications.document",
                verbose_name="Documents",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.consularoffice",
                verbose_name="Bureau consulaire",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.servicetype",
                verbose_name="Service",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "-created_at"], name="application_status_db7a61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["applicant", "-created_at"],
                name="application_applica_58ad8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["reference_number"], name="application_referen_56abf0_idx"
            ),
        ),
    ]
