# Generated by Django 4.2.11 on 2025-10-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="ID de transaction",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant (XOF)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CARD", "Carte bancaire"),
                            ("STRIPE", "Stripe"),
                            ("ORANGE", "Orange Money"),
                            ("WAVE", "Wave"),
                            ("TRANSFER", "Virement bancaire"),
                            ("CASH", "Espèces"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="ID transaction fournisseur",
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Référence fournisseur"
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Réponse fournisseur"
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Numéro de reçu",
                    ),
                ),
                (
                    "receipt_url",
                    models.URLField(blank=True, verbose_name="URL du reçu"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notes administratives"),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Raison de l'échec"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_id",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="ID de remboursement",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant remboursé",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motif du remboursement")),
                (
                    "provider_refund_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="ID remboursement fournisseur",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                        verbose_name="Paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remboursement",
                "verbose_name_plural": "Remboursements",
                "ordering": ["-created_at"],
            },
        ),
    ]
