# Generated by Django 4.2.11 on 2025-10-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_certificate_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numéro d'acte de naissance"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="children_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre d'enfants"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="driving_license_expiry",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'expiration permis"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="driving_license_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numéro de permis de conduire"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="employer",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Employeur"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="id_card_expiry",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'expiration carte d'identité"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="id_card_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numéro de carte d'identité"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Célibataire"),
                    ("married", "Marié(e)"),
                    ("divorced", "Divorcé(e)"),
                    ("widowed", "Veuf/Veuve"),
                ],
                max_length=20,
                verbose_name="Statut matrimonial",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profession",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Profession"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="spouse_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom du conjoint"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone professionnel"
            ),
        ),
    ]
