# Generated by Django 4.2.11 on 2025-10-13 14:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_birth_certificate_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_profile_complete",
            field=models.BooleanField(default=False, verbose_name="Profil complet"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Contact d'urgence - Nom"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Contact d'urgence - Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin"), ("O", "Autre")],
                max_length=10,
                verbose_name="Sexe",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nationalité"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Email vérifié"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format de numéro de téléphone invalide.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code de vérification email",
                "verbose_name_plural": "Codes de vérification email",
                "ordering": ["-created_at"],
            },
        ),
    ]
