# Generated by Django 4.2.11 on 2025-10-13 22:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_remove_user_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passeport"),
                            ("id_card", "Carte d'identité"),
                            ("consular_card", "Carte consulaire"),
                            ("driving_license", "Permis de conduire"),
                            ("birth_certificate", "Acte de naissance"),
                            ("marriage_certificate", "Acte de mariage"),
                            ("other", "Autre document"),
                        ],
                        max_length=50,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du document"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="user_documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'upload"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document utilisateur",
                "verbose_name_plural": "Documents utilisateur",
                "ordering": ["-upload_date"],
            },
        ),
    ]
