# Generated by Django 4.2.11 on 2025-10-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CITIZEN", "Citoyen"),
                    ("AGENT_RDV", "Agent Rendez-vous"),
                    ("AGENT_CONSULAIRE", "Agent Consulaire"),
                    ("VIGILE", "Vigile/Sécurité"),
                    ("ADMIN", "Administrateur"),
                    ("SUPERADMIN", "Super Administrateur"),
                ],
                default="CITIZEN",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
