# Generated by Django 4.2.11 on 2025-10-25 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('days_until_expiry', models.IntegerField(verbose_name='Jours avant expiration')),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent (< 3 jours)'), ('HIGH', 'Important (< 7 jours)'), ('MEDIUM', 'Rappel (< 30 jours)')], max_length=10, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('COMPLETED', 'Traité'), ('IGNORED', 'Ignoré')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi email")),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification envoyée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='users.userdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rappel de document',
                'verbose_name_plural': 'Rappels de documents',
                'ordering': ['expiry_date', '-priority'],
                'unique_together': {('document', 'user')},
            },
        ),
    ]
