# Generated by Django 4.2.11 on 2025-10-28 18:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_documentreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(default=users.models.EmailVerificationCode.default_expiry),
        ),
    ]
