# Generated by Django 4.2.11 on 2025-11-21 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_emailverificationcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consular_card_number',
            field=models.CharField(blank=True, help_text='Format: SN suivi de 7 à 9 chiffres (ex: SN1234567)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Format de numéro de carte consulaire invalide. Format attendu: SN suivi de 7 à 9 chiffres (ex: SN1234567)', regex='^SN\\d{7,9}$')], verbose_name='Numéro de carte consulaire'),
        ),
    ]
