# Generated by Django 4.2.11 on 2025-11-22 17:12

import core.encrypted_fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_consular_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_phone',
            field=core.encrypted_fields.EncryptedCharField(blank=True, help_text='Chiffré en base de données', max_length=200, verbose_name="Contact d'urgence - Téléphone"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_phone',
            field=core.encrypted_fields.EncryptedCharField(blank=True, help_text='Chiffré en base de données', max_length=200, verbose_name='Téléphone professionnel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='consular_card_number',
            field=core.encrypted_fields.EncryptedCharField(blank=True, help_text='Format: SN suivi de 7 à 9 chiffres (ex: SN1234567) - Chiffré en base de données', max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Format de numéro de carte consulaire invalide. Format attendu: SN suivi de 7 à 9 chiffres (ex: SN1234567)', regex='^SN\\d{7,9}$')], verbose_name='Numéro de carte consulaire'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Format de numéro de téléphone invalide.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
