# Generated by Django 4.2.11 on 2025-11-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_birth_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_first_names',
            field=models.JSONField(blank=True, default=list, help_text='Liste des prénoms supplémentaires (ex: ["Marie", "Sophie"])', verbose_name='Prénoms supplémentaires'),
        ),
        migrations.AddField(
            model_name='profile',
            name='additional_last_names',
            field=models.JSONField(blank=True, default=list, help_text='Liste des noms de famille supplémentaires (ex: ["Dupont", "Martin"])', verbose_name='Noms de famille supplémentaires'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_last_name',
            field=models.CharField(blank=True, help_text='Nom de famille à la naissance', max_length=200, verbose_name='Nom de naissance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='used_last_name',
            field=models.CharField(blank=True, help_text="Nom d'usage (nom utilisé actuellement)", max_length=200, verbose_name="Nom d'usage"),
        ),
    ]
