# Generated by Django 4.2.11 on 2025-11-22 20:33

import core.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_additional_first_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_certificate_number',
            field=core.encrypted_fields.EncryptedCharField(blank=True, help_text='Chiffré en base de données', max_length=200, null=True, verbose_name="Numéro d'acte de naissance"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='driving_license_number',
            field=core.encrypted_fields.EncryptedCharField(blank=True, help_text='Chiffré en base de données', max_length=200, null=True, verbose_name='Numéro de permis de conduire'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card_number',
            field=core.encrypted_fields.EncryptedCharField(blank=True, help_text='Chiffré en base de données', max_length=200, null=True, verbose_name="Numéro de carte d'identité"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=core.encrypted_fields.EncryptedCharField(blank=True, help_text='Chiffré en base de données', max_length=200, null=True, verbose_name='Numéro de passeport'),
        ),
    ]
