# Generated by Django 4.2.11 on 2025-12-29 07:34

import core.encrypted_fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_null_to_encrypted_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=512, validators=[django.core.validators.RegexValidator(message='Format de numéro de téléphone invalide.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
