# Generated by Django 4.2.11 on 2025-12-29 08:21

import core.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_certificate_number_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Hash acte naissance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='consular_number_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Hash numéro consulaire'),
        ),
        migrations.AddField(
            model_name='profile',
            name='driving_license_number_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Hash permis'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_card_number_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Hash carte identité'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_number_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Hash passeport'),
        ),
        migrations.AddField(
            model_name='user',
            name='consular_card_number_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Hash carte consulaire'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_certificate_number',
            field=core.encrypted_fields.EncryptedTextField(blank=True, help_text='Chiffré en base de données', null=True, verbose_name="Numéro d'acte de naissance"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='consular_number',
            field=core.encrypted_fields.EncryptedTextField(blank=True, help_text='Chiffré en base de données', null=True, verbose_name='Numéro consulaire'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='driving_license_number',
            field=core.encrypted_fields.EncryptedTextField(blank=True, help_text='Chiffré en base de données', null=True, verbose_name='Numéro de permis de conduire'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_name',
            field=models.TextField(blank=True, verbose_name="Contact d'urgence - Nom"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact_phone',
            field=core.encrypted_fields.EncryptedTextField(blank=True, help_text='Chiffré en base de données', verbose_name="Contact d'urgence - Téléphone"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employer',
            field=models.TextField(blank=True, verbose_name='Employeur'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card_number',
            field=core.encrypted_fields.EncryptedTextField(blank=True, help_text='Chiffré en base de données', null=True, verbose_name="Numéro de carte d'identité"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=core.encrypted_fields.EncryptedTextField(blank=True, help_text='Chiffré en base de données', null=True, verbose_name='Numéro de passeport'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place_of_birth',
            field=models.TextField(blank=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.TextField(blank=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spouse_name',
            field=models.TextField(blank=True, verbose_name='Nom du conjoint'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_phone',
            field=core.encrypted_fields.EncryptedTextField(blank=True, help_text='Chiffré en base de données', verbose_name='Téléphone professionnel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='consular_card_number',
            field=core.encrypted_fields.EncryptedTextField(blank=True, help_text='Format: SN suivi de 7 à 9 chiffres (ex: SN1234567) - Chiffré en base de données', null=True, verbose_name='Numéro de carte consulaire'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=core.encrypted_fields.EncryptedTextField(blank=True, help_text='Chiffré en base de données', verbose_name='Numéro de téléphone'),
        ),
    ]
