# Generated by Django 4.2.11 on 2025-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("NORMAL", "Normale"),
                            ("HIGH", "Haute"),
                            ("URGENT", "Urgente"),
                        ],
                        default="NORMAL",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Épinglé"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "publish_from",
                    models.DateTimeField(verbose_name="Date de publication"),
                ),
                (
                    "publish_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "target_all_users",
                    models.BooleanField(default=True, verbose_name="Visible par tous"),
                ),
                (
                    "target_roles",
                    models.CharField(
                        blank=True,
                        help_text="Rôles ciblés (séparés par des virgules)",
                        max_length=200,
                        verbose_name="Rôles ciblés",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-is_pinned", "-priority", "-publish_from"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("VIEW", "Consultation"),
                            ("APPROVE", "Approbation"),
                            ("REJECT", "Rejet"),
                            ("DOWNLOAD", "Téléchargement"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("PAYMENT", "Paiement"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date et heure"
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journaux d'audit",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ConsularOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "office_type",
                    models.CharField(
                        choices=[
                            ("EMBASSY", "Ambassade"),
                            ("CONSULATE", "Consulat"),
                            ("SECTION", "Section Consulaire"),
                        ],
                        default="EMBASSY",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="Adresse ligne 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse ligne 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Sénégal", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(max_length=20, verbose_name="Téléphone principal"),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone secondaire"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone d'urgence"
                    ),
                ),
                (
                    "opening_hours",
                    models.TextField(
                        blank=True,
                        help_text="Horaires d'ouverture (ex: Lun-Ven 9h-17h)",
                        verbose_name="Horaires d'ouverture",
                    ),
                ),
                (
                    "jurisdiction_countries",
                    models.TextField(
                        blank=True,
                        help_text="Pays couverts par cette ambassade/consulat",
                        verbose_name="Juridiction",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "accepts_appointments",
                    models.BooleanField(
                        default=True, verbose_name="Accepte les rendez-vous"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bureau Consulaire",
                "verbose_name_plural": "Bureaux Consulaires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VISA", "Visa"),
                            ("PASSPORT", "Passeport"),
                            ("GENERAL", "Général"),
                            ("APPOINTMENT", "Rendez-vous"),
                            ("PAYMENT", "Paiement"),
                            ("DOCUMENTS", "Documents"),
                        ],
                        default="GENERAL",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Réponse")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["category", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.CharField(max_length=100, verbose_name="Page")),
                (
                    "context",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Contexte"
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[("POSITIVE", "Positif"), ("NEGATIVE", "Négatif")],
                        max_length=10,
                        verbose_name="Avis",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Traité"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notes admin"),
                ),
            ],
            options={
                "verbose_name": "Retour utilisateur",
                "verbose_name_plural": "Retours utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du service"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VISA", "Visa"),
                            ("PASSPORT", "Passeport"),
                            ("CIVIL", "Actes Civils"),
                            ("LEGAL", "Légalisation"),
                            ("ATTEST", "Attestation"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "required_documents",
                    models.TextField(
                        blank=True,
                        help_text="Liste des documents requis (un par ligne)",
                        verbose_name="Documents requis",
                    ),
                ),
                (
                    "base_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Frais de base (XOF)",
                    ),
                ),
                (
                    "processing_time_days",
                    models.IntegerField(
                        default=5,
                        help_text="Délai de traitement estimé en jours",
                        verbose_name="Délai de traitement",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "requires_appointment",
                    models.BooleanField(
                        default=True, verbose_name="Nécessite rendez-vous"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offices",
                    models.ManyToManyField(
                        related_name="services",
                        to="core.consularoffice",
                        verbose_name="Bureaux offrant ce service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de Service",
                "verbose_name_plural": "Types de Services",
                "ordering": ["display_order", "category", "name"],
            },
        ),
    ]
