# Generated by Django 4.2.11 on 2025-11-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('APPROVE', 'Approbation'), ('REJECT', 'Rejet'), ('DOWNLOAD', 'Téléchargement'), ('LOGIN', 'Connexion'), ('LOGIN_FAILED', 'Tentative de connexion échouée'), ('LOGOUT', 'Déconnexion'), ('PAYMENT', 'Paiement'), ('CHANGE_ROLE', 'Changement de rôle'), ('ACTIVATE_USER', 'Activation utilisateur'), ('DEACTIVATE_USER', 'Désactivation utilisateur'), ('PASSWORD_RESET', 'Réinitialisation mot de passe')], max_length=20, verbose_name='Action'),
        ),
    ]
