# Generated by Django 4.2.11 on 2025-11-21 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_enabled', models.BooleanField(default=True, help_text="Permet aux nouveaux utilisateurs de s'inscrire", verbose_name='Inscription activée')),
                ('registration_message', models.TextField(default="Merci de votre sollicitude. Nous vous prions de passer à l'ambassade pour effectuer cette tâche.", help_text="Message affiché lorsque l'inscription est désactivée", verbose_name="Message d'inscription désactivée")),
                ('appointments_enabled', models.BooleanField(default=True, help_text='Permet aux utilisateurs de prendre des rendez-vous', verbose_name='Rendez-vous activés')),
                ('appointments_message', models.TextField(default="Merci de votre sollicitude. Nous vous prions de passer à l'ambassade pour effectuer cette tâche.", verbose_name='Message rendez-vous désactivés')),
                ('applications_enabled', models.BooleanField(default=True, help_text='Permet aux utilisateurs de soumettre des demandes', verbose_name='Demandes activées')),
                ('applications_message', models.TextField(default="Merci de votre sollicitude. Nous vous prions de passer à l'ambassade pour effectuer cette tâche.", verbose_name='Message demandes désactivées')),
                ('payments_enabled', models.BooleanField(default=True, help_text="Permet aux utilisateurs d'effectuer des paiements en ligne", verbose_name='Paiements activés')),
                ('payments_message', models.TextField(default="Merci de votre sollicitude. Nous vous prions de passer à l'ambassade pour effectuer cette tâche.", verbose_name='Message paiements désactivés')),
                ('site_maintenance_mode', models.BooleanField(default=False, help_text='Désactive toutes les fonctionnalités publiques (sauf connexion admin)', verbose_name='Mode maintenance')),
                ('maintenance_message', models.TextField(default='Le site est actuellement en maintenance. Merci de votre compréhension.', verbose_name='Message de maintenance')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-timestamp'], name='core_auditl_ip_addr_71e206_idx'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_updates', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='single_site_settings'),
        ),
    ]
